/*
 * This source file was generated by the Gradle 'init' task
 */
package d2;
/**
 * Class App which containts the main function.
 * 
 * @author Batuhan Seker
 * @version 1.0
 * @since 2024
 */
public class App {
    /**
     * Main function creates a "Flug" object, 3 "Passagier" objects and calling their associated functions.
     * @param args
     */
    public static void main(String[] args) {
        Flug f = new Flug();
        Passagier p1 = new Passagier("Hans");
        Passagier p2 = new Passagier("Peter");
        Passagier p3 = new Passagier("Hans");
        f.passagierHinzufügen(p1);
        f.passagierHinzufügen(p2);
        f.passagierHinzufügen(p3);
        f.passagierHinzufügen(p3);
        f.passagierEntfernen(p3);
        f.passagierEntfernen(p3);
        
        f.passagierListeAusgeben();
    }
}
