/*
 * This source file was generated by the Gradle 'init' task
 */
package v3;

public class App {

    public static void main(String[] args) {
        BoerseNy ny = new BoerseNy();
        BoerseZh zh = new BoerseZh();

        Portfolio portfolioNy = new Portfolio(ny);
        Portfolio portfolioZh = new Portfolio(zh);

        portfolioNy.setPrice();
        portfolioZh.setPrice();

        System.out.println("New York Portfolio: ");
        System.out.println("---------------------");
        System.out.println("Nvidia: "+ portfolioNy.nvidia + "$");
        System.out.println("Microsoft: " +portfolioNy.microsoft + "$");
        System.out.println(" ");
        System.out.println("Zürich Portfolio: ");
        System.out.println("---------------------");
        System.out.println("Nvidia: "+ portfolioZh.nvidia + "CHF");
        System.out.println("Microsoft: "+portfolioZh.microsoft+ "CHF");

        

    }
}
