/*
 * This source file was generated by the Gradle 'init' task
 */
package v2;


/**
 * The App class represnt our main entry.
 * 
 * @author Batuhan Seker
 * @version 1.0
 * @since 2024
 */
public class App {

    /**
     * Creates the `Manschaft`object.
     * 
     * @param args
     */
    public static void main(String[] args) {
        Mannschaft mannschaft = new Mannschaft();
    }
}
