/*
 * This source file was generated by the Gradle 'init' task
 */
package d3;

public class App {

    public static void main(String[] args) {
        UserInterface ui = new UserInterface();
        ui.start();
    }
}
